name: Upload Website
on:
  push: # The workflow will run on every push even on the repository
jobs:
  build: # The CI part
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2 # Downloading Git code
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
  deploy: # The CD part
    needs: build # Set a depency in the build stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master # Use GitHub Action to deploy the code on Amazon Web Services (S3)
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # optional: defaults to us-east-1
